language: generic
sudo: false
matrix:
  include:
    - env: RUNTIME=2.7 TOOLKIT=pyqt
    - env: RUNTIME=2.7 TOOLKIT=pyside
    - env: RUNTIME=2.7 TOOLKIT=wx
    - env: RUNTIME=3.5 TOOLKIT=pyqt
    - os: osx
      env: RUNTIME=2.7 TOOLKIT=pyqt
    - os: osx
      env: RUNTIME=2.7 TOOLKIT=pyside
    - os: osx
      env: RUNTIME=2.7 TOOLKIT=wx
    - os: osx
      env: RUNTIME=3.5 TOOLKIT=pyqt
  fast_finish: true
cache:
  directories:
    - $HOME/.cache
before_install:
  - export PATH=/usr/lib/ccache:${PATH}
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - if [[ ${TRAVIS_PYTHON_VERSION} == "3.4" && ${ETS_TOOLKIT} == "qt4" ]]; then ./build_pyside_wheel.sh; fi
  - pip install -r travis-ci-requirements.txt
install:
  - python setup.py develop
before_script:
  - mkdir testrun
  - cp .coveragerc testrun/
  - cd testrun
script:
  - coverage run -m nose.core -v pyface --exclude=${EXCLUDE}
after_success:
  - pip install codecov
  - codecov
