language: generic
sudo: false
matrix:
  include:
    - env: RUNTIME=2.7 TOOLKITS="pyqt pyside wx"
    - env: RUNTIME=3.5 TOOLKITS="pyqt pyqt5"
    - os: osx
      env: RUNTIME=2.7 TOOLKITS="pyqt pyside wx"
    - os: osx
      env: RUNTIME=3.5 TOOLKITS="pyqt pyqt5"
cache:
  directories:
    - $HOME/.cache
before_install:
  - export DISPLAY=:99.0; 
  - if [[ ${TRAVIS_OS_NAME} == 'linux' ]]; then sh -e /etc/init.d/xvfb start; fi
  - ./travis_ci_bootstrap_edm.sh
install:
  - for TOOLKIT in ${TOOLKITS}; do edm run -- invoke install --runtime=${RUNTIME} --toolkit=${TOOLKIT}; done
script:
  - for TOOLKIT in ${TOOLKITS}; do edm run -- invoke test --runtime=${RUNTIME} --toolkit=${TOOLKIT}; done
after_success:
  - edm run -- pip install codecov
  - edm run -- codecov
