language: generic
sudo: false

env:
  global:
    - INSTALL_EDM_VERSION=1.9.1
      PYTHONUNBUFFERED="1"

matrix:
  include:
    - env: RUNTIME=2.7 TOOLKITS="pyqt pyside wx"
    - env: RUNTIME=3.5 TOOLKITS="pyqt pyqt5"
    - env: RUNTIME=3.6 TOOLKITS="pyqt pyqt5"
    - os: osx
      env: RUNTIME=2.7 TOOLKITS="pyqt pyside wx"
    - os: osx
      env: RUNTIME=3.5 TOOLKITS=pyqt
cache:
  directories:
    - $HOME/.cache
before_install:
  - mkdir -p "${HOME}/.cache/download"
  - export DISPLAY=:99.0; 
  - if [[ ${TRAVIS_OS_NAME} == "linux" ]] ; then sh -e /etc/init.d/xvfb start; fi
  - if [[ ${TRAVIS_OS_NAME} == 'linux' ]]; then ./install-edm-linux.sh; export PATH="${HOME}/edm/bin:${PATH}"; fi
  - if [[ ${TRAVIS_OS_NAME} == 'osx' ]]; then ./install-edm-osx.sh; export PATH="${PATH}:/usr/local/bin"; fi
  - edm install -y pip invoke coverage
install:
  - for toolkit in ${TOOLKITS}; do edm run -- invoke install --runtime=${RUNTIME} --toolkit=${toolkit}; done
script:
  - declare -i RESULT=0
  - for toolkit in ${TOOLKITS}; do edm run -- invoke test --runtime=${RUNTIME} --toolkit=${toolkit}; RESULT+=$?; done
after_success:
  - edm run -- coverage combine
  - edm run -- pip install codecov
  - edm run -- codecov
