language: python
sudo: false
python:
  - 2.7_with_system_site_packages
  - 3.4
addons:
  apt:
    packages:
    - libegl1-mesa
    - libegl1-mesa-dev
    - libegl1-mesa-drivers
    - python-pip
    - python-numpy
    - python-wxtools
    - ccache
    - cmake
env:
  global:
    - BUILD_PREFIX=$HOME/build-prefix
    - BINDIR=$BUILD_PREFIX/bin
    - LIBDIR=$BUILD_PREFIX/lib
    - INCDIR=$BUILD_PREFIX/include
    - PATH=$BINDIR:$PATH
    - LD_LIBRARY_PATH=$LIBDIR
    - PYTHONPATH=$BUILD_PREFIX/lib/python2.7/site-packages:$BUILD_PREFIX/lib/python3.4/site-packages
    - CFLAGS="-I$INCDIR -L$LIBDIR"
    - CXXFLAGS="-I$INCDIR -L$LIBDIR"
  matrix:
    - ETS_TOOLKIT=qt4 EXCLUDE=wx QT_API=pyside
    - ETS_TOOLKIT=qt4 EXCLUDE=wx QT_API=pyqt
    - ETS_TOOLKIT=qt4 EXCLUDE=wx QT_API=pyqt5
    - ETS_TOOLKIT=wx EXCLUDE=qt
matrix:
  allow_failures:
    - python: 3.4
      env: ETS_TOOLKIT=wx EXCLUDE=qt
    - python: 3.4
      env: ETS_TOOLKIT=qt4 EXCLUDE=wx QT_API=pyqt
    - python: 3.4
      env: ETS_TOOLKIT=qt4 EXCLUDE=wx QT_API=pyqt5
cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache
before_install:
  - ccache -s
  - pip install --upgrade pip
  - export PATH=/usr/lib/ccache:${PATH}
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - if [[ ${ETS_TOOLKIT} == "qt4" ]]; then ./build_qt_bindings.sh ; fi
  - pip install -r travis-ci-requirements.txt
install:
  - python setup.py develop
before_script:
  - mkdir testrun
  - cp .coveragerc testrun/
  - cd testrun
script:
  - env
  - python -m site
  - if [ "${QT_API#pyqt}" != "${QT_API}" ] ; then python -c "import sip; print(sip)" ; fi
  - if [ "$QT_API" = "pyqt5" ] ; then python -c "import PyQt5.QtWidgets; print(PyQt5.QtWidgets.QApplication([]))" ; fi
  - coverage run -m nose -v pyface --exclude=${EXCLUDE}
after_success:
  - pip install codecov
  - codecov
