language: python
sudo: false
python:
  - 2.7
addons:
  apt:
    packages:
    - python-qt4
    - python-qt4-gl
    - python-pip
    - python-numpy
    - python-wxtools
    - ccache
env:
  - ETS_TOOLKIT=qt4 EXCLUDE=wx
  - ETS_TOOLKIT=wx EXCLUDE=qt
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache
virtualenv:
  system_site_packages: true
before_install:
  - ccache -s
  - pip install --upgrade pip
  - export PATH=/usr/lib/ccache:${PATH}
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pip install pygments
  - pip install traits
  - pip install traitsui
  - pip install traits_enaml
  - pip install enaml
  - pip install nose-exclude
  - pip install coverage
  - pip install codecov
  - python setup.py develop
  - coverage run -m nose.core -v --exclude-dir=pyface/ui/${EXCLUDE} --exclude="enaml"
  - if [[ ${ETS_TOOLKIT} == "qt4" ]]; then coverage run -a -m nose.core -v pyface/tasks/tests/*enaml*; fi
after_success:
  - codecov