language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-qt4
install:
  - pip install traits
  - pip install coverage
  - python setup.py develop
script:
  - coverage -m nose.core -v
after_success:
  - coverage report