language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-qt4
install:
  - pip install traits
  - pip install coverage
  - pip install codecov
  - python setup.py develop
script:
  - export DISPLAY=:99.0
  - /etc/init.d/xvfb start
  - ETS_TOOKIT=qt4 coverage run -m nose.core -v
after_success:
  - codecov