language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-qt4 python-wxgtk2.8
install:
  - pip install pygments
  - pip install traits
  - pip install traitsui
  - pip install traits_enaml
  - pip install enaml
  - pip install nose-exclude
  - pip install coverage
  - pip install codecov
  - python setup.py develop
script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - ETS_TOOLKIT=qt4 coverage run -m nose.core -v --exclude-dir=pyface/ui/wx --exclude="enaml"
  - ETS_TOOLKIT=qt4 coverage run -a -m nose.core -v pyface/tasks/tests/*enaml*
  - ETS_TOOLKIT=wx coverage run -a -m nose.core -v --exclude-dir=pyface/ui/qt4
after_success:
  - codecov