language: python
sudo: false
python:
  - 2.7_with_system_site_packages
  - 3.4
addons:
  apt:
    packages:
    - python-pip
    - python-numpy
    - python-wxtools
    - ccache
    - cmake
env:
  - ETS_TOOLKIT=qt4 EXCLUDE=wx QT_API=pyside
  - ETS_TOOLKIT=qt4 EXCLUDE=wx QT_API=pyqt
  - ETS_TOOLKIT=qt4 EXCLUDE=wx QT_API=pyqt5
  - ETS_TOOLKIT=wx EXCLUDE=qt4
matrix:
  allow_failures:
    - python: 3.4
      env: ETS_TOOLKIT=wx EXCLUDE=qt4
    - python: 3.4
      env: ETS_TOOLKIT=qt4 EXCLUDE=wx QT_API=pyqt
    - python: 3.4
      env: ETS_TOOLKIT=qt4 EXCLUDE=wx QT_API=pyqt5
cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache
before_install:
  - ccache -s
  - pip install --upgrade pip
  - export PATH=/usr/lib/ccache:${PATH}
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - if [[ ${ETS_TOOLKIT} == "qt4" ]]; then ./build_qt_bindings_wheel.sh ; fi
  - pip install -r travis-ci-requirements.txt
install:
  - python setup.py develop
before_script:
  - mkdir testrun
  - cp .coveragerc testrun/
  - cd testrun
script:
  - coverage run -m nose.core -v pyface --exclude=${EXCLUDE}
after_success:
  - pip install codecov
  - codecov
